In [1]:
import pandas as pd
import numpy as np 
pd.set_option('display.max_columns', None) # para poder visualizar todas las columnas de los DataFrames

In [2]:
df_goodreads_top100 = pd.read_csv ('files/goodreads_top100_from1980to2023_final.csv', index_col=0)

In [3]:
df_goodreads_top100

,isbn,title,series_title,series_release_number,authors,publisher,language,description,num_pages,format,genres,publication_date,rating_score,num_ratings,num_reviews,current_readers,want_to_read,price,url
0,9780689830594,Summer Story,Brambly Hedge,2,Jill Barklem,Atheneum,English,It was such a hot summer. The sky was deep blu...,32,Hardcover,"['Picture Books', 'Childrens', 'Fiction', 'Ani...","January 1, 1980",4.45,1017.0,74.0,7.0,512.0,3.49,https://www.goodreads.com/book/show/421572.Sum...
1,9780375704970,The Lake of Darkness,NaN,NaN,Ruth Rendell,Vintage Crime/Black Lizard,English,Martin Urban is a quiet bachelor with a comfor...,210,Paperback,"['Mystery', 'Fiction', 'Crime', 'Thriller', 'B...","January 1, 1980",3.76,1388.0,114.0,77.0,623.0,4.99,https://www.goodreads.com/book/show/83394.The_...
2,9780345446671,Beyond the Blue Event Horizon,Heechee Saga,2,Frederik Pohl,Ballantine Books,English,"In Book Two of the Heechee Saga, Robinette Bro...",336,Paperback,"['Science Fiction', 'Fiction', 'Space Opera', ...","January 1, 1980",3.95,13307.0,339.0,181.0,3961.0,11.99,https://www.goodreads.com/book/show/373399.Bey...
3,9780446403016,St. Peter's Fair,Chronicles of Brother Cadfael,4,Ellis Peters,Mysterious Press,English,A pause in the civil war offers Shrewsbury's t...,217,Mass Market Paperback,"['Mystery', 'Historical Fiction', 'Fiction', '...","May 1, 1981",4.12,10493.0,593.0,1298.0,2502.0,0.00,https://www.goodreads.com/book/show/751755.St_...
4,9780425198773,Twice Shy,NaN,NaN,Dick Francis,G.P. Putnam's Sons,English,A computerized horse-betting system falls into...,304,Mass Market Paperback,"['Mystery', 'Fiction', 'Thriller', 'Crime', 'S...","January 1, 1981",3.92,4188.0,174.0,162.0,642.0,8.99,https://www.goodreads.com/book/show/103250.Twi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4395,9781451648218,Murder Your Employer: The McMasters Guide to H...,NaN,NaN,Rupert Holmes,Avid Reader Press / Simon & Schuster,English,A devilish thriller with a killer concept: The...,389,Hardcover,"['Mystery', 'Fiction', 'Thriller', 'Mystery Th...","February 21, 2023",3.89,20992.0,3479.0,4033.0,84900.0,12.99,https://www.goodreads.com/book/show/61272658-m...
4396,9781250826978,System Collapse,The Murderbot Diaries,7,Martha Wells,Tor Publishing Group/Tordotcom,English,Everyone's favorite lethal SecUnit is back.\nF...,245,Hardcover,"['Science Fiction', 'Fiction', 'Audiobook', 'A...","November 13, 2023",4.24,26566.0,3479.0,3609.0,36600.0,11.99,https://www.goodreads.com/book/show/65211701-s...
4397,9781496737298,"Georgie, All Along",NaN,NaN,Kate Clayborn,Kensington,English,A wise and witty new novel that echoes with ti...,340,Paperback,"['Romance', 'Fiction', 'Contemporary', 'Contem...","January 24, 2023",3.82,48031.0,6590.0,3180.0,76300.0,0.00,https://www.goodreads.com/book/show/60604190-g...
4398,9780525619994,Sword Catcher,Sword Catcher,1,Cassandra Clare,Del Rey Books,English,"In the vibrant city-state of Castellane, the r...",624,Hardcover,"['Fantasy', 'Romance', 'Adult', 'Young Adult',...","October 10, 2023",3.84,14991.0,3523.0,4485.0,149000.0,14.99,https://www.goodreads.com/book/show/36679274-s...
4399,9780593239919,"Poverty, by America",NaN,NaN,Matthew Desmond,Crown,English,"The Pulitzer Prize–winning, bestselling author...",284,Hardcover,"['Nonfiction', 'Politics', 'Sociology', 'Histo...","March 21, 2023",4.30,28248.0,4007.0,6021.0,133000.0,13.99,https://www.goodreads.com/book/show/61358638-p...

In [4]:
df_goodreads_top100.columns

Index(['isbn', 'title', 'series_title', 'series_release_number', 'authors',
       'publisher', 'language', 'description', 'num_pages', 'format', 'genres',
       'publication_date', 'rating_score', 'num_ratings', 'num_reviews',
       'current_readers', 'want_to_read', 'price', 'url'],
      dtype='object')

In [5]:
df_goodreads_top100.duplicated().sum()

61

In [6]:
df_goodreads_top100.drop_duplicates (inplace = True)
df_goodreads_top100

,isbn,title,series_title,series_release_number,authors,publisher,language,description,num_pages,format,genres,publication_date,rating_score,num_ratings,num_reviews,current_readers,want_to_read,price,url
0,9780689830594,Summer Story,Brambly Hedge,2,Jill Barklem,Atheneum,English,It was such a hot summer. The sky was deep blu...,32,Hardcover,"['Picture Books', 'Childrens', 'Fiction', 'Ani...","January 1, 1980",4.45,1017.0,74.0,7.0,512.0,3.49,https://www.goodreads.com/book/show/421572.Sum...
1,9780375704970,The Lake of Darkness,NaN,NaN,Ruth Rendell,Vintage Crime/Black Lizard,English,Martin Urban is a quiet bachelor with a comfor...,210,Paperback,"['Mystery', 'Fiction', 'Crime', 'Thriller', 'B...","January 1, 1980",3.76,1388.0,114.0,77.0,623.0,4.99,https://www.goodreads.com/book/show/83394.The_...
2,9780345446671,Beyond the Blue Event Horizon,Heechee Saga,2,Frederik Pohl,Ballantine Books,English,"In Book Two of the Heechee Saga, Robinette Bro...",336,Paperback,"['Science Fiction', 'Fiction', 'Space Opera', ...","January 1, 1980",3.95,13307.0,339.0,181.0,3961.0,11.99,https://www.goodreads.com/book/show/373399.Bey...
3,9780446403016,St. Peter's Fair,Chronicles of Brother Cadfael,4,Ellis Peters,Mysterious Press,English,A pause in the civil war offers Shrewsbury's t...,217,Mass Market Paperback,"['Mystery', 'Historical Fiction', 'Fiction', '...","May 1, 1981",4.12,10493.0,593.0,1298.0,2502.0,0.00,https://www.goodreads.com/book/show/751755.St_...
4,9780425198773,Twice Shy,NaN,NaN,Dick Francis,G.P. Putnam's Sons,English,A computerized horse-betting system falls into...,304,Mass Market Paperback,"['Mystery', 'Fiction', 'Thriller', 'Crime', 'S...","January 1, 1981",3.92,4188.0,174.0,162.0,642.0,8.99,https://www.goodreads.com/book/show/103250.Twi...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4395,9781451648218,Murder Your Employer: The McMasters Guide to H...,NaN,NaN,Rupert Holmes,Avid Reader Press / Simon & Schuster,English,A devilish thriller with a killer concept: The...,389,Hardcover,"['Mystery', 'Fiction', 'Thriller', 'Mystery Th...","February 21, 2023",3.89,20992.0,3479.0,4033.0,84900.0,12.99,https://www.goodreads.com/book/show/61272658-m...
4396,9781250826978,System Collapse,The Murderbot Diaries,7,Martha Wells,Tor Publishing Group/Tordotcom,English,Everyone's favorite lethal SecUnit is back.\nF...,245,Hardcover,"['Science Fiction', 'Fiction', 'Audiobook', 'A...","November 13, 2023",4.24,26566.0,3479.0,3609.0,36600.0,11.99,https://www.goodreads.com/book/show/65211701-s...
4397,9781496737298,"Georgie, All Along",NaN,NaN,Kate Clayborn,Kensington,English,A wise and witty new novel that echoes with ti...,340,Paperback,"['Romance', 'Fiction', 'Contemporary', 'Contem...","January 24, 2023",3.82,48031.0,6590.0,3180.0,76300.0,0.00,https://www.goodreads.com/book/show/60604190-g...
4398,9780525619994,Sword Catcher,Sword Catcher,1,Cassandra Clare,Del Rey Books,English,"In the vibrant city-state of Castellane, the r...",624,Hardcover,"['Fantasy', 'Romance', 'Adult', 'Young Adult',...","October 10, 2023",3.84,14991.0,3523.0,4485.0,149000.0,14.99,https://www.goodreads.com/book/show/36679274-s...
4399,9780593239919,"Poverty, by America",NaN,NaN,Matthew Desmond,Crown,English,"The Pulitzer Prize–winning, bestselling author...",284,Hardcover,"['Nonfiction', 'Politics', 'Sociology', 'Histo...","March 21, 2023",4.30,28248.0,4007.0,6021.0,133000.0,13.99,https://www.goodreads.com/book/show/61358638-p...

In [7]:
df_goodreads_top100['isbn'].duplicated().sum()

721

In [8]:
df_goodreads_top100['title'].duplicated().sum()

199

In [9]:
df_goodreads_top100['isbn'].isna().sum()

588

In [10]:
(df_goodreads_top100.isnull().sum() / df_goodreads_top100.shape[0]) * 100

isbn                     13.551510
title                     0.000000
series_title             48.444342
series_release_number    48.720903
authors                   0.000000
publisher                 2.673427
language                  0.576170
description               0.046094
num_pages                 0.483982
format                    0.806637
genres                    0.000000
publication_date          0.023047
rating_score              0.000000
num_ratings               0.000000
num_reviews               0.000000
current_readers           2.396866
want_to_read              0.875778
price                     5.277714
url                       0.000000
dtype: float64

In [11]:
df_goodreads_top100[df_goodreads_top100 ['title'] == 'Twice Shy']

,isbn,title,series_title,series_release_number,authors,publisher,language,description,num_pages,format,genres,publication_date,rating_score,num_ratings,num_reviews,current_readers,want_to_read,price,url
4,9780425198773,Twice Shy,NaN,NaN,Dick Francis,G.P. Putnam's Sons,English,A computerized horse-betting system falls into...,304,Mass Market Paperback,"['Mystery', 'Fiction', 'Thriller', 'Crime', 'S...","January 1, 1981",3.92,4188.0,174.0,162.0,642.0,8.99,https://www.goodreads.com/book/show/103250.Twi...
171,9780425198773,Twice Shy,NaN,NaN,Dick Francis,G.P. Putnam's Sons,English,A computerized horse-betting system falls into...,304,Mass Market Paperback,"['Mystery', 'Fiction', 'Thriller', 'Crime', 'S...","January 1, 1981",3.92,4194.0,175.0,162.0,644.0,8.99,https://www.goodreads.com/book/show/103250.Twi...
4198,9780593085530,Twice Shy,NaN,NaN,Sarah Hogle,G.P. Putnam's Sons,English,Can you find real love when you've always got ...,302,Paperback,"['Romance', 'Contemporary', 'Contemporary Roma...","April 6, 2021",3.68,33132.0,6056.0,856.0,62500.0,11.99,https://www.goodreads.com/book/show/54660653-t...

In [12]:
df_goodreads_top100['series_title'].value_counts()

In Death                         17
Chronicles of Brother Cadfael    15
Black Dagger Brotherhood         15
Vorkosigan Saga                  14
Redwall                          14
                                 ..
Little Brother                    1
Love Walked In                    1
Olive Kitteridge                  1
Wyoming                           1
Sword Catcher                     1
Name: series_title, Length: 1098, dtype: int64

In [13]:
df_goodreads_top100['series_release_number'].value_counts()

1         788
2         429
3         293
4         153
5         100
         ...
1-4         1
26,5        1
29,6        1
8,11        1
1,10.5      1
Name: series_release_number, Length: 101, dtype: int64

In [14]:
df_goodreads_top100['language'].value_counts()

English               4277
French                  14
Spanish; Castilian      10
German                   7
Japanese                 2
Dutch; Flemish           2
Danish                   1
Portuguese               1
Name: language, dtype: int64

In [15]:
df_goodreads_top100['authors'].duplicated().sum()

2433

In [16]:
df_goodreads_top100['publisher'].isna().sum()

116

In [17]:
df_goodreads_top100['language'].isna().sum()

25

In [18]:
df_goodreads_top100['language'] = df_goodreads_top100['language'].fillna("Unknown")

In [19]:
df_goodreads_top100['description'].isna().sum()

2

In [20]:
df_goodreads_top100['description'] = df_goodreads_top100['description'].fillna("Unknown")

In [21]:
df_goodreads_top100['num_pages'].isna().sum()

21

In [22]:
df_goodreads_top100['num_pages'] = df_goodreads_top100['num_pages'].fillna("Unknown")

In [23]:
df_goodreads_top100['format'].value_counts()

Paperback                1740
Hardcover                1387
Mass Market Paperback     706
Kindle Edition            276
ebook                     131
Nook                       14
Audio CD                   11
Library Binding             8
Board Book                  7
Audio Cassette              5
Board book                  5
Trade Paperback             5
Unknown Binding             2
Audiobook                   2
hardcover                   1
paper                       1
Slipcased Hardcover         1
Print                       1
Broschiert                  1
Name: format, dtype: int64

In [24]:
df_goodreads_top100['format'].isna().sum()

35

In [25]:
df_goodreads_top100['format'] = df_goodreads_top100['format'].fillna("Unknown")

In [26]:
df_goodreads_top100['genres'].value_counts()

['Fantasy', 'Fiction', 'Young Adult', 'Childrens', 'Animals', 'Adventure', 'Middle Grade']        12
['Fiction', 'Young Adult', 'Childrens', 'Middle Grade', 'Fantasy', 'Mystery', 'Adventure']        11
['Mystery', 'Crime', 'Fiction', 'Thriller', 'Mystery Thriller', 'Suspense', 'Murder Mystery']     10
[]                                                                                                10
['Mystery', 'Fiction', 'Crime', 'Thriller', 'Detective', 'Mystery Thriller', 'Suspense']          10
                                                                                                  ..
['Picture Books', 'Childrens', 'Fiction', 'Animals', 'Humor', 'Dogs', 'School']                    1
['Fiction', 'Contemporary', 'Romance', 'Chick Lit', 'Drama', 'Adult Fiction', 'Adult']             1
['Nonfiction', 'Law', 'History', 'True Crime', 'Environment', 'Crime', 'Science']                  1
['Mystery', 'Fiction', 'Cats', 'Cozy Mystery', 'Animals', 'Crime', 'Audiobook']                    1
['Nonfiction', 'Politics', 'Sociology', 'History', 'Economics', 'Audiobook', 'Social Justice']     1
Name: genres, Length: 3625, dtype: int64

In [32]:
df_goodreads_top100[df_goodreads_top100['publication_date'].isna()]

,isbn,title,series_title,series_release_number,authors,publisher,language,description,num_pages,format,genres,publication_date,rating_score,num_ratings,num_reviews,current_readers,want_to_read,price,url
4087,9781838056124,The Present,VanWest,2,Kenneth Thomas,NaN,English,Old Version,200,Paperback,"['Science Fiction', 'Fiction', 'Dystopia', 'Yo...",NaN,3.62,2395.0,80.0,18.0,1995.0,NaN,https://www.goodreads.com/book/show/54775299-t...

In [41]:
df_eliminar = df_goodreads_top100[df_goodreads_top100 ['isbn'] == '9781838056124']

In [ ]:
df_goodreads_top100['publication_date'].value_counts()

January 1, 1984       58
January 1, 1986       57
January 1, 1990       55
January 1, 1983       55
January 1, 1982       52
                      ..
August 15, 2006        1
September 25, 2006     1
July 18, 2006          1
June 27, 2006          1
March 21, 2023         1
Name: publication_date, Length: 1983, dtype: int64

In [ ]:
df_goodreads_top100['publication_date'] = df_goodreads_top100['publication_date'].str.replace('Published ', '')

In [ ]:
# Convertimos la columna 'publication_date' al formato de fecha
df_goodreads_top100['publication_date'] = pd.to_datetime(df_goodreads_top100['publication_date'])

In [ ]:
# Creamos nuevas columnas para el mes y el año
df_goodreads_top100['publication_month'] = df_goodreads_top100['publication_date'].dt.month
df_goodreads_top100['publication_year'] = df_goodreads_top100['publication_date'].dt.year

In [ ]:
df_goodreads_top100.head()

,isbn,title,series_title,series_release_number,authors,publisher,language,description,num_pages,format,genres,publication_date,rating_score,num_ratings,num_reviews,current_readers,want_to_read,price,url,publication_month,publication_year
0,9780689830594,Summer Story,Brambly Hedge,2,Jill Barklem,Atheneum,English,It was such a hot summer. The sky was deep blu...,32,Hardcover,"['Picture Books', 'Childrens', 'Fiction', 'Ani...",1980-01-01,4.45,1017.0,74.0,7.0,512.0,3.49,https://www.goodreads.com/book/show/421572.Sum...,1.0,1980.0
1,9780375704970,The Lake of Darkness,NaN,NaN,Ruth Rendell,Vintage Crime/Black Lizard,English,Martin Urban is a quiet bachelor with a comfor...,210,Paperback,"['Mystery', 'Fiction', 'Crime', 'Thriller', 'B...",1980-01-01,3.76,1388.0,114.0,77.0,623.0,4.99,https://www.goodreads.com/book/show/83394.The_...,1.0,1980.0
2,9780345446671,Beyond the Blue Event Horizon,Heechee Saga,2,Frederik Pohl,Ballantine Books,English,"In Book Two of the Heechee Saga, Robinette Bro...",336,Paperback,"['Science Fiction', 'Fiction', 'Space Opera', ...",1980-01-01,3.95,13307.0,339.0,181.0,3961.0,11.99,https://www.goodreads.com/book/show/373399.Bey...,1.0,1980.0
3,9780446403016,St. Peter's Fair,Chronicles of Brother Cadfael,4,Ellis Peters,Mysterious Press,English,A pause in the civil war offers Shrewsbury's t...,217,Mass Market Paperback,"['Mystery', 'Historical Fiction', 'Fiction', '...",1981-05-01,4.12,10493.0,593.0,1298.0,2502.0,0.00,https://www.goodreads.com/book/show/751755.St_...,5.0,1981.0
4,9780425198773,Twice Shy,NaN,NaN,Dick Francis,G.P. Putnam's Sons,English,A computerized horse-betting system falls into...,304,Mass Market Paperback,"['Mystery', 'Fiction', 'Thriller', 'Crime', 'S...",1981-01-01,3.92,4188.0,174.0,162.0,642.0,8.99,https://www.goodreads.com/book/show/103250.Twi...,1.0,1981.0

In [ ]:
dict_meses = meses_dict = {
    1.0: 'enero',
    2.0: 'febrero',
    3.0: 'marzo',
    4.0: 'abril',
    5.0: 'mayo',
    6.0: 'junio',
    7.0: 'julio',
    8.0: 'agosto',
    9.0: 'septiembre',
    10.0: 'octubre',
    11.0: 'noviembre',
    12.0: 'diciembre'
}

In [ ]:
df_goodreads_top100['publication_month'].map (dict_meses)

0           enero
1           enero
2           enero
3            mayo
4           enero
          ...
4395      febrero
4396    noviembre
4397        enero
4398      octubre
4399        marzo
Name: publication_month, Length: 4339, dtype: object

In [ ]:
df_goodreads_top100['publication_date'] = df_goodreads_top100['publication_date'].fillna(1.0)

In [ ]:
df_goodreads_top100['publication_year'].astype (int)

IntCastingNaNError: Cannot convert non-finite values (NA or inf) to integer

In [ ]:
df_goodreads_top100['publication_date'] = df_goodreads_top100['publication_date'].fillna("Unknown")